apiVersion: v1
kind: Service
metadata:
  name: jobportal-app-service1
spec:
  type: NodePort
  selector:
    app: jobportal-app
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 31122 # You can change this to any available port number above 30000